#version: '3'  # version of compose format

services:
  meals-service:
    build: ./meals  # path is relative to docker-compose-shorthand.yml location
    restart: always   # possible values for restart are:  "no", always, on-failure, unless-stopped
    volumes:
      - type: bind
        source: ./meals #host directory
        target: /meals # container directory
    environment:
      # tells flask run to run in development mode and reload the code on change. This mode should only be used in
      # development.
      FLASK_DEBUG: "true"
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "5001:80"  # host:container
    # expose:
    #  - 80
    depends_on:
      - mongo
  diets-service:
    build: ./diets  # path is relative to docker-compose-shorthand.yml location
    restart: always   # possible values for restart are:  "no", always, on-failure, unless-stopped
    volumes:
      - type: bind
        source: ./diets #host directory
        target: /diets # container directory
    environment:
      # tells flask run to run in development mode and reload the code on change. This mode should only be used in
      # development.
      FLASK_DEBUG: "true"
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "5002:80"  # host:container
    expose:
      - 80
    depends_on:
      - mongo  
  reverse:
    build: ./reverse
    ports:
      - "80:80"  # host:container
    depends_on: # website is not going to work unless these services are running.
      - diets-service
      - meals-service
  mongo:
    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017